# Generated by Django 4.2 on 2023-04-07 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usercreatedpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=255)),
                ('page_description', models.TextField(blank=True)),
                ('theme_photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('location', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Stores.usercreatedpage')),
            ],
        ),
        migrations.CreateModel(
            name='Service_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('service_price', models.FloatField()),
                ('location', models.CharField(max_length=255)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('page_owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Userservices', to='Stores.usercreatedpage')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.FloatField()),
                ('stock_available', models.IntegerField()),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('page_owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Userproducts', to='Stores.usercreatedpage')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
