# Generated by Django 4.2 on 2023-04-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0002_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='merchant_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
