# Generated by Django 4.1 on 2023-05-16 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0010_ordered'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ordered',
        ),
    ]
