# Generated by Django 4.1 on 2023-05-16 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0011_delete_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_from',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderfrom', to='Stores.order'),
        ),
        migrations.CreateModel(
            name='Ordered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Stores.order')),
            ],
        ),
    ]
