# Generated by Django 4.1 on 2023-05-22 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0012_alter_orderitem_order_from_ordered'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ordered',
        ),
    ]
