# Generated by Django 4.1 on 2023-05-23 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0013_delete_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderfrom', to='Stores.order'),
        ),
    ]
