# Generated by Django 4.1 on 2023-05-23 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0017_alter_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_from',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orderfrom', to='Stores.order'),
        ),
    ]
