# Generated by Django 4.1 on 2023-06-07 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0018_remove_orderitem_order_from_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_info',
            name='page_owner',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Userproducts', to='Stores.usercreatedpage'),
        ),
    ]
