# Generated by Django 4.1 on 2023-06-07 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0019_alter_product_info_page_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_info',
            name='page_owner',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Userproducts', to='Stores.usercreatedpage'),
        ),
    ]
