# Generated by Django 4.1 on 2023-06-10 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0021_tariffs_tariff_query_location_gambia'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffs',
            name='page_owner',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tariff_page_owner', to='Stores.usercreatedpage'),
        ),
    ]
