# Generated by Django 4.1 on 2023-06-14 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0022_tariffs_page_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_gambia',
            name='page_owner',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='locations_page', to='Stores.usercreatedpage'),
        ),
    ]
