# Generated by Django 4.1 on 2023-06-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0023_location_gambia_page_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffs',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
