# Generated by Django 4.1 on 2023-06-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0024_tariffs_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreatedpage',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
