# Generated by Django 4.1 on 2023-06-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0025_usercreatedpage_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
