# Generated by Django 4.1 on 2023-06-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0026_order_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_info',
            name='product_description',
            field=models.TextField(max_length=2600, null=True),
        ),
    ]
