# Generated by Django 4.1 on 2023-06-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0027_product_info_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_info',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='service_info',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='usercreatedpage',
            name='page_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usercreatedpage',
            name='theme_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
