# Generated by Django 4.1 on 2023-07-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0028_alter_product_info_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='abuko',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='bakau',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='bakoteh',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='banjul',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='banjulinding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='barra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='batokunku',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='bijilo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='brikama',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='brufut_Taf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='brufut_heights',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='brusubi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='bundung',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='busumbala',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='churchill_Town',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='coastal_Road',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='dalaba_estate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='dippa_kunda',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='ebou_town',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='fajara',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='faji_kunda',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='faraba',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='farato',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='gunjur',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='jabang',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='jambanjelly',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='jamburr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='jimpex',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='kanifing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='kartong',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='kerr_sering',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='kololi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='kotu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='lamin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='latrikunda_german',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='latrikunda_sabigi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='latriya',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='madinabaa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='madinari',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='madiyana',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='manjai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='marakesa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='mariamakunda',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='nema_su',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='new_jeshwang',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='old_jeshwang',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='old_yundum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='paradise_estate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='paradise_view',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='pipline',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='salaji',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='sanchaba',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='sanyang',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='senegambia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='serekunda',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='sinchu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='sukuta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='tabokoto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='tallinding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='tanji',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='tipper_garage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='traffic_lights',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='tujereng',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='turntable',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='westfield',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='wulinkama',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='yarambamba',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='yuna',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_gambia',
            name='yundum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
