# Generated by Django 4.1 on 2023-07-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0029_order_phone_number_alter_location_gambia_abuko_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_info',
            name='image_url2',
            field=models.ImageField(blank=True, default='no-photo.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product_info',
            name='image_url3',
            field=models.ImageField(blank=True, default='no-photo.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product_info',
            name='image_url4',
            field=models.ImageField(blank=True, default='no-photo.png', null=True, upload_to=''),
        ),
    ]
