# Generated by Django 4.1 on 2023-08-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0030_product_info_image_url2_product_info_image_url3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreatedpage',
            name='theme_photo',
            field=models.ImageField(blank=True, default='no_image.jpg', null=True, upload_to=''),
        ),
    ]
