# Generated by Django 4.1 on 2023-10-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0035_alter_location_gambia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_gambia',
            name='wellingara',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
