# Generated by Django 4.1 on 2023-11-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0038_alter_usercreatedpage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreatedpage',
            name='id',
            field=models.CharField(max_length=155, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
