# Generated by Django 4.1 on 2023-11-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0039_alter_usercreatedpage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_info',
            name='product_description',
            field=models.TextField(blank=True, max_length=2600, null=True),
        ),
        migrations.AlterField(
            model_name='product_info',
            name='stock_available',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
